services:
  app:
    image: solar-works-job-nimbus:latest
    build:
      context: .
      args:
        BUILD_ENV: prod
    container_name: solar-works-job-nimbus
    volumes:
      - ./creds/${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/${GOOGLE_APPLICATION_CREDENTIALS}
      - ./data:/app/data
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/${GOOGLE_APPLICATION_CREDENTIALS}
      K_SERVICE: dev
      K_CONFIGURATION: dev
      K_REVISION: dev-00001
      USERNAME: ${USERNAME}
      JN_PWD: ${JN_PWD}
      PYTHON_ENV: prod

    ports:
      - '8080:8080'
    user: '0'
