import { Pipeline } from './pipeline.interface';
import { transformFloat, transformDateTime } from '../pipeline.transform';

export const completedInstalls: Pipeline = {
    url: 'https://app.jobnimbus.com/report/281d586193ca499499a880f8badc8a45?view=1',
    transformFn: (row) => ({
        name: row['Name'],
        location: row['Location'],
        installation_date: transformDateTime(row['Installation Date']),
        project_manager: row['Project Manager'],
        site_assessment_date: transformDateTime(row['Site Assessment Date']),
        panel_type: row['Panel Type'],
        numberofmodules: transformFloat(row['Numberofmodules']),
        most_recent_budget_revenue: row['Most Recent Budget Revenue'],
        status: row['Status'],
        city: row['City'],
        state: row['State'],
        lender: row['Lender'],
        record_type: row['Record Type'],
        date_status_change: transformDateTime(row['Date Status Change']),
        sales_rep: row['Sales Rep'],
        number: row['Number'],
        address_line: row['Address Line'],
        address_line2: row['Address Line2'],
        zip: row['Zip'],
        id: row['Id'],
        related: row['Related'],
        primary: row['Primary'],
        task_id: row['Task Id'],
        job_id: row['Job Id'],
        contact_id: row['Contact Id'],
    }),
    loadOptions: {
        table: 'CompletedInstalls',
        schema: [
            { name: 'name', type: 'STRING' },
            { name: 'location', type: 'STRING' },
            { name: 'installation_date', type: 'TIMESTAMP' },
            { name: 'project_manager', type: 'STRING' },
            { name: 'site_assessment_date', type: 'TIMESTAMP' },
            { name: 'panel_type', type: 'STRING' },
            { name: 'numberofmodules', type: 'NUMERIC' },
            { name: 'most_recent_budget_revenue', type: 'STRING' },
            { name: 'status', type: 'STRING' },
            { name: 'city', type: 'STRING' },
            { name: 'state', type: 'STRING' },
            { name: 'lender', type: 'STRING' },
            { name: 'record_type', type: 'STRING' },
            { name: 'date_status_change', type: 'TIMESTAMP' },
            { name: 'sales_rep', type: 'STRING' },
            { name: 'number', type: 'STRING' },
            { name: 'address_line', type: 'STRING' },
            { name: 'address_line2', type: 'STRING' },
            { name: 'zip', type: 'STRING' },
            { name: 'id', type: 'STRING' },
            { name: 'related', type: 'STRING' },
            { name: 'primary', type: 'STRING' },
            { name: 'task_id', type: 'STRING' },
            { name: 'job_id', type: 'STRING' },
            { name: 'contact_id', type: 'STRING' },
        ],
        writeDisposition: 'WRITE_TRUNCATE',
    },
};
